### ISSUE TITLE
Looking forward to this awesome work

### ISSUE THREAD

**Issue by Aaronhuang-778** [scottgeng00/unmet-promise#1]
Hi, Scott

Thanks for your nice work, and i am looking forward to the code about this work. Your work provides unique insights into applications of synthetic data :-)

**Comment by scottgeng00** [comment]
Hi Wei,

Thank you for your interest in our work, and thank you very much for your patience. Our code is now ready. Please let us know if you have any questions or if you encounter any issues. We hope you'll find our work useful!
